version: "3"

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.8
    command:
      - "--api.insecure=true"
      # - "--accesslog=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
    ports:
      # DNS
      - 53:53/tcp
      - 53:53/udp
      # DHCP server
      # - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
      # HTTPS/DNS-over-HTTPS
      # - 443:443/tcp
      # DNS-over-TLS
      - 853:853/tcp
      # WebUI
      - 8092:80/tcp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.local`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=8092"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./hass:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hass.rule=Host(`hass.local`)"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
      - JELLYFIN_PublishedServerUrl=192.168.50.101 #optional
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /media:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./syncthing:/config
      - /home/pi/Sync:/data1
    ports:
      # - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.local`)"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"

  paperless-ngx:
    image: lscr.io/linuxserver/paperless-ngx:latest
    container_name: paperless-ngx
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
    volumes:
      - ./paperless/config:/config
      - ./paperless/data:/data
    ports:
      - 8091:8000
    restart: unless-stopped
    labels:
      - "traefik.http.routers.paperless.rule=Host(`paperless.local`)"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
