version: "3"

networks:
  web-proxy:
    external: true

services:
  # Reverse proxy server
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      # - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=web-proxy
    networks:
      - web-proxy
    # extra_hosts:
      # - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy:/data
    restart: unless-stopped
    # labels:
    #   caddy_0: adguard.local
    #   caddy_0.reverse_proxy: host.docker.internal:3000

  # Network wide adblock
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: always
    network_mode: host
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf

  # Home automation
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: host
    volumes:
      - ./hass:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  # Media center
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - web-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
      - JELLYFIN_PublishedServerUrl=192.168.50.101 #optional
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /mnt/wintorrents:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped
