version: "3"

networks:
  web-proxy:
    external: true

services:
  traefik:
    container_name: traefik
    image: traefik:v2.8
    restart: always
    networks:
      - web-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./rules.yml:/rules.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks:
      - web-proxy
    ports:
      - 9000:9000 # web access
      - 9443:9443 # secure web access
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=secure,insecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  # Network wide adblock (setup admin port on 8021)
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: always
    network_mode: host
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
    labels: # Check rules.yml
      - "traefik.enable=true"
      - "traefik.http.services.adguard.loadbalancer.server.port=8021"

  # Home automation
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    network_mode: host
    volumes:
      - ./hass:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels: # Check rules.yml
      - "traefik.enable=true"
      - "traefik.http.services.hass.loadbalancer.server.port=8123"

  # Media center
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - web-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
      - JELLYFIN_PublishedServerUrl=192.168.50.101 #optional
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /mnt/wintorrents:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
